ant -f projects/net-sf-tweety-action/update_latest_build.xml
ant -f projects/net-sf-tweety-action-description-c/update_latest_build.xml
ant -f projects/net-sf-tweety-action-query-s/update_latest_build.xml
ant -f projects/net-sf-tweety-agents/update_latest_build.xml
ant -f projects/net-sf-tweety-agents-dialoguesystems/update_latest_build.xml
ant -f projects/net-sf-tweety-argumentation-deductive/update_latest_build.xml
ant -f projects/net-sf-tweety-argumentation-delp/update_latest_build.xml
ant -f projects/net-sf-tweety-argumentation-dung/update_latest_build.xml
ant -f projects/net-sf-tweety-argumentation-structuredargumentationframeworks/update_latest_build.xml
ant -f projects/net-sf-tweety-beliefdynamics/update_latest_build.xml
ant -f projects/net-sf-tweety-cli/update_latest_build.xml
ant -f projects/net-sf-tweety-graphs/update_latest_build.xml
ant -f projects/net-sf-tweety-logicprogramming-asp/update_latest_build.xml
ant -f projects/net-sf-tweety-logics-commons/update_latest_build.xml
ant -f projects/net-sf-tweety-logics-conditionallogic/update_latest_build.xml
ant -f projects/net-sf-tweety-logics-firstorderlogic/update_latest_build.xml
ant -f projects/net-sf-tweety-logics-markovlogic/update_latest_build.xml
ant -f projects/net-sf-tweety-logics-modallogic/update_latest_build.xml
ant -f projects/net-sf-tweety-logics-probabilisticconditionallogic/update_latest_build.xml
ant -f projects/net-sf-tweety-logics-propositionallogic/update_latest_build.xml
ant -f projects/net-sf-tweety-logics-relationalconditionallogic/update_latest_build.xml
ant -f projects/net-sf-tweety-logics-relationalprobabilisticconditionallogic/update_latest_build.xml
ant -f projects/net-sf-tweety-math/update_latest_build.xml
ant -f projects/net-sf-tweety-preferences/update_latest_build.xml
ant -f projects/net-sf-tweety/update_latest_build.xml
ant -f projects/net-sf-tweety/update_latest_build_\(complete\).xml
