/* Generated By:JavaCC: Do not edit this line. ELPParserConstants.java */
package net.sf.tweety.logicprogramming.asplibrary.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ELPParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DOT = 6;
  /** RegularExpression Id. */
  int COLON = 7;
  /** RegularExpression Id. */
  int LBRA = 8;
  /** RegularExpression Id. */
  int RBRA = 9;
  /** RegularExpression Id. */
  int SQLBRA = 10;
  /** RegularExpression Id. */
  int SQRBRA = 11;
  /** RegularExpression Id. */
  int CURLBRA = 12;
  /** RegularExpression Id. */
  int CURRBRA = 13;
  /** RegularExpression Id. */
  int PIPE = 14;
  /** RegularExpression Id. */
  int LOGIMPL = 15;
  /** RegularExpression Id. */
  int WEAKIMPL = 16;
  /** RegularExpression Id. */
  int NUMBER = 17;
  /** RegularExpression Id. */
  int DIGIT = 18;
  /** RegularExpression Id. */
  int NOT = 19;
  /** RegularExpression Id. */
  int TEXTOR = 20;
  /** RegularExpression Id. */
  int SYMBOL = 21;
  /** RegularExpression Id. */
  int VAR = 22;
  /** RegularExpression Id. */
  int CHAR = 23;
  /** RegularExpression Id. */
  int UCHAR = 24;
  /** RegularExpression Id. */
  int BLANK = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\".\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"|\"",
    "\":-\"",
    "\":~\"",
    "<NUMBER>",
    "<DIGIT>",
    "\"not\"",
    "\"v\"",
    "<SYMBOL>",
    "<VAR>",
    "<CHAR>",
    "<UCHAR>",
    "\"_\"",
    "\",\"",
    "\"=\"",
    "\"<=\"",
    "\"<\"",
    "\">=\"",
    "\">\"",
    "\"!=\"",
    "\"+\"",
    "\"*\"",
    "\"-\"",
  };

}
