package net.sf.tweety.agents.sim;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import net.sf.tweety.agents.AbstractProtocol;
import net.sf.tweety.agents.Agent;
import net.sf.tweety.agents.MultiAgentSystem;
import net.sf.tweety.agents.ProtocolTerminatedException;

/**
 * This class implements a game simulator. It takes some agent and multi-agent system generators
 * and runs a series of simulations. In each simulation the winner of the game is determined and
 * recorded.
 * @author Matthias Thimm
 * @param <T> The actual type of agents.
 * @param <S> The actual type of protocols.
 */
public class GameSimulator<S extends AbstractProtocol & GameProtocol, T extends Agent, R extends MultiAgentSystem<T>> {

	/** The multi-agent system generator. */
	private MultiAgentSystemGenerator<T,R> masGenerator;
	/** The protocol generator. */
	private ProtocolGenerator<S,T,R> protGenerator;
	/** The agent generators. */
	private List<AgentGenerator<T,R>> agentGenerators;
	
	/**
	 * Creates a new GameSimulator for the given
	 * MultiAgentSystemGenerator and AgentGenerators.
	 * @param masGenerator a MultiAgentSystemGenerator 
	 * @param protGenerator a protocol generator
	 * @param agentGenerators some AgentGenerators.
	 */
	public GameSimulator(MultiAgentSystemGenerator<T,R> masGenerator, ProtocolGenerator<S,T,R> protGenerator, List<AgentGenerator<T,R>> agentGenerators){
		this.masGenerator = masGenerator;
		this.agentGenerators = agentGenerators;
		this.protGenerator = protGenerator;
	}
	
	/**
	 * Simulates the game for the given number of
	 * repetitions and returns a map indicating
	 * which agent generator won how often.
	 * @param repetitions the number of repetitions.
	 * @return a map which assigns to each agent generator
	 *  the number of times an agent generated by it won the game.
	 * @throws ProtocolTerminatedException if a protocol is asked
	 *  to perform a step but has already terminated. 
	 */
	public Map<AgentGenerator<T,R>, Integer> run(int repetitions) throws ProtocolTerminatedException{
		Map<AgentGenerator<T,R>,Integer> wins = new HashMap<AgentGenerator<T,R>,Integer>();
		Map<Agent,AgentGenerator<T,R>> a2ag = new HashMap<Agent,AgentGenerator<T,R>>();
		for(AgentGenerator<T,R> ag: this.agentGenerators)
			wins.put(ag, 0);
		for(int i = 0; i < repetitions; i++){
			SimulationParameters params = new SimulationParameters();
			R mas = this.masGenerator.generate(params);
			S prot = this.protGenerator.generate(mas,params);
			// create agents
			for(AgentGenerator<T,R> ag: this.agentGenerators){
				T a = ag.generate(mas,params);
				mas.add(a);
				a2ag.put(a, ag);
			}		
			mas.execute(prot);	
			if(prot.hasWinner()){
				Agent a = prot.getWinner();
				AgentGenerator<T,R> ag = a2ag.get(a);
				wins.put(ag, wins.get(ag) + 1);
			}
		}		
		return wins;
	}
}
